using Firebase.Auth;
using Firebase.Extensions;
using Firebase.Firestore;
using System.Collections.Generic;
using UnityEngine;

// This class implements the IAuthSystem interface to handle cloud-based authentication operations
public class FirebaseAuthManager : IAuthSystem
{
    private FirebaseAuth auth = FirebaseAuth.DefaultInstance;

    // Public method to register a new user using an email and password string
    public void SignUp(string email, string password, string displayName, System.Action<string> onSuccess)
    {
        // Start an asynchronous process on the network server to create a new user profile with the provided credentials
        auth.CreateUserWithEmailAndPasswordAsync(email, password).ContinueWithOnMainThread(task => {

            // Check if the background network thread failed to complete or was manually aborted mid-process
            if (task.IsFaulted || task.IsCanceled)
            {
                // Print a critical error message containing the server exception data directly to the log window
                Debug.LogError("Signup Failed: " + task.Exception);

                // Exit out of the callback method early since the registration process did not succeed
                return;
            }

            // Extract the unique identification string generated by the cloud server for this newly registered profile
            string newId = task.Result.User.UserId;

            // Print a success log displaying the fresh identity code to verify a valid connection
            Debug.Log("Auth Success: " + newId);

            // Trigger the success notification callback and safely pass the unique identifier code back to the managing listener
            onSuccess?.Invoke(newId);
        });
    }

    // Public method to verify credentials and log into an existing user profile
    public void Login(string email, string password)
    {
        // Start an asynchronous process on the network server to match and validate the user credentials
        auth.SignInWithEmailAndPasswordAsync(email, password).ContinueWithOnMainThread(task => {

            // Check if the server verification process finished executing without running into a network fault
            if (task.IsCompleted && !task.IsFaulted)
            {
                // Print a confirmation message showing the verified profile email address to confirm a successful connection
                Debug.Log("User Logged in: " + task.Result.User.Email);
            }
        });
    }

    // Public method to check and return the currently active user authentication signature
    public string GetUserID()
    {
        // Evaluate if a profile is currently active; if true, return the unique account identity code, otherwise return an empty string
        return auth.CurrentUser != null ? auth.CurrentUser.UserId : "";
    }
}